//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexConfirmMail.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexConfirmMail.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap banner {
            get {
                object obj = ResourceManager.GetObject("banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static string RibbonButtonFlexConfirmMail {
            get {
                return ResourceManager.GetString("RibbonButtonFlexConfirmMail", resourceCulture);
            }
        }

        public static string RibbonGroupFlexConfirmMail {
            get {
                return ResourceManager.GetString("RibbonGroupFlexConfirmMail", resourceCulture);
            }
        }

        public static string SaveAndQuit {
            get {
                return ResourceManager.GetString("SaveAndQuit", resourceCulture);
            }
        }

        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }

        public static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }

        public static string ConfigGeneral {
            get {
                return ResourceManager.GetString("ConfigGeneral", resourceCulture);
            }
        }

        public static string ConfigCount {
            get {
                return ResourceManager.GetString("ConfigCount", resourceCulture);
            }
        }

        public static string ConfigCountEnabled {
            get {
                return ResourceManager.GetString("ConfigCountEnabled", resourceCulture);
            }
        }

        public static string ConfigCountAllowSkip {
            get {
                return ResourceManager.GetString("ConfigCountAllowSkip", resourceCulture);
            }
        }

        public static string ConfigCountSeconds {
            get {
                return ResourceManager.GetString("ConfigCountSeconds", resourceCulture);
            }
        }

        public static string ConfigWarning {
            get {
                return ResourceManager.GetString("ConfigWarning", resourceCulture);
            }
        }

        public static string ConfigSafeBccEnabled {
            get {
                return ResourceManager.GetString("ConfigSafeBccEnabled", resourceCulture);
            }
        }

        public static string ConfigSafeBccThreshold {
            get {
                return ResourceManager.GetString("ConfigSafeBccThreshold", resourceCulture);
            }
        }

        public static string ConfigSafeBccThresholdSuffix {
            get {
                return ResourceManager.GetString("ConfigSafeBccThresholdSuffix", resourceCulture);
            }
        }

        public static string ConfigMisc {
            get {
                return ResourceManager.GetString("ConfigMisc", resourceCulture);
            }
        }

        public static string ConfigMainSkipIfNoExt {
            get {
                return ResourceManager.GetString("ConfigMainSkipIfNoExt", resourceCulture);
            }
        }

        public static string ConfigTrustedDomains {
            get {
                return ResourceManager.GetString("ConfigTrustedDomains", resourceCulture);
            }
        }

        public static string TrustedDomainsPolicy {
            get {
                return ResourceManager.GetString("TrustedDomainsPolicy", resourceCulture);
            }
        }

        public static string UnsafeDomainsPolicy{
            get {
                return ResourceManager.GetString("UnsafeDomainsPolicy", resourceCulture);
            }
        }

        public static string UnsafeFilesPolicy {
            get {
                return ResourceManager.GetString("UnsafeFilesPolicy", resourceCulture);
            }
        }

        public static string TrustedDomainsExample {
            get {
                return ResourceManager.GetString("TrustedDomainsExample", resourceCulture);
            }
        }

        public static string UnsafeDomainsExample {
            get {
                return ResourceManager.GetString("UnsafeDomainsExample", resourceCulture);
            }
        }

        public static string UnsafeFilesExample {
            get {
                return ResourceManager.GetString("UnsafeFilesExample", resourceCulture);
            }
        }

        public static string TrustedDomainsTemplate {
            get {
                return ResourceManager.GetString("TrustedDomainsTemplate", resourceCulture);
            }
        }

        public static string UnsafeDomainsTemplate {
            get {
                return ResourceManager.GetString("UnsafeDomainsTemplate", resourceCulture);
            }
        }

        public static string UnsafeFilesTemplate {
            get {
                return ResourceManager.GetString("UnsafeFilesTemplate", resourceCulture);
            }
        }

        public static string TrustedDomains {
            get {
                return ResourceManager.GetString("TrustedDomains", resourceCulture);
            }
        }

        public static string ConfigUnsafeDomains {
            get {
                return ResourceManager.GetString("ConfigUnsafeDomains", resourceCulture);
            }
        }

        public static string UnsafeDomains {
            get {
                return ResourceManager.GetString("UnsafeDomains", resourceCulture);
            }
        }

        public static string ConfigUnsafeFiles {
            get {
                return ResourceManager.GetString("ConfigUnsafeFiles", resourceCulture);
            }
        }

        public static string UnsafeFiles {
            get {
                return ResourceManager.GetString("UnsafeFiles", resourceCulture);
            }
        }

        public static string AboutAddon {
            get {
                return ResourceManager.GetString("AboutAddon", resourceCulture);
            }
        }

        public static string TextLog {
            get {
                return ResourceManager.GetString("TextLog", resourceCulture);
            }
        }

        public static string CountWindowTitle {
            get {
                return ResourceManager.GetString("CountWindowTitle", resourceCulture);
            }
        }

        public static string CountSendInSeconds {
            get {
                return ResourceManager.GetString("CountSendInSeconds", resourceCulture);
            }
        }

        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }

        public static string SendNow {
            get {
                return ResourceManager.GetString("SendNow", resourceCulture);
            }
        }

        public static string MainExternal {
            get {
                return ResourceManager.GetString("MainExternal", resourceCulture);
            }
        }

        public static string MainUnsafeDomainsWarning {
            get {
                return ResourceManager.GetString("MainUnsafeDomainsWarning", resourceCulture);
            }
        }

        public static string MainUnsafeDomainsWarningHint {
            get {
                return ResourceManager.GetString("MainUnsafeDomainsWarningHint", resourceCulture);
            }
        }

        public static string MainUnsafeFilesWarning {
            get {
                return ResourceManager.GetString("MainUnsafeFilesWarning", resourceCulture);
            }
        }

        public static string MainUnsafeFilesWarningHint {
            get {
                return ResourceManager.GetString("MainUnsafeFilesWarningHint", resourceCulture);
            }
        }

        public static string MainSafeBccWarning {
            get {
                return ResourceManager.GetString("MainSafeBccWarning", resourceCulture);
            }
        }

        public static string MainSafeBccWarningHint {
            get {
                return ResourceManager.GetString("MainSafeBccWarningHint", resourceCulture);
            }
        }

        public static string MainFilesWarning {
            get {
                return ResourceManager.GetString("MainFilesWarning", resourceCulture);
            }
        }

        public static string MainTrusted {
            get {
                return ResourceManager.GetString("MainTrusted", resourceCulture);
            }
        }

        public static string MainCheckAll {
            get {
                return ResourceManager.GetString("MainCheckAll", resourceCulture);
            }
        }

        public static string MainFile {
            get {
                return ResourceManager.GetString("MainFile", resourceCulture);
            }
        }
    }
}
